services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/
    tty: true
    user: vscode:vscode
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./..:/workspace:cached
      - $HOME/.ssh:/home/vscode/.ssh

# I should start a sql service as well

